name: Cypress Tests

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-with-chrome:
    name: Cypress with Chrome
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npx cypress run
          browser: chrome

  cypress-with-firefox:
    name: Cypress with Firefox
    needs:
      - Cypress with Chrome
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npx cypress run
          browser: firefox
